FROM liquibase/liquibase
# RUN ls -l /liquibase/internal/lib
# RUN rm -rf /liquibase/internal/lib/snowflake-jdbc.jar
# RUN rm -rf /liquibase/internal/lib/sqlite-jdbc.jar
# RUN rm -rf /liquibase/internal/lib/h2.jar
# RUN rm -rf /liquibase/internal/lib/hsqldb.jar
# RUN rm -rf /liquibase/internal/lib/jaybird.jar
# RUN rm -rf /liquibase/internal/lib/mssql-jdbc.jar
# RUN rm -rf /liquibase/internal/lib/postgresql.jar
# RUN rm -rf /liquibase/internal/lib/liquibase-commercial.jar
COPY ./singlestore-jdbc-client-1.1.4.jar /liquibase/internal/lib/

